"""create members, bank_accounts, consents, documents tables

Revision ID: 5fd753c458ee
Revises: 
Create Date: 2026-07-17 09:56:38.282157

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fd753c458ee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('title', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('membership_type', sa.String(length=20), nullable=False),
    sa.Column('family_member_name', sa.String(length=200), nullable=True),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('signed_place', sa.String(length=100), nullable=True),
    sa.Column('signed_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index(op.f('ix_members_id'), 'members', ['id'], unique=False)
    op.create_table('bank_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('account_holder_name', sa.String(length=200), nullable=False),
    sa.Column('street', sa.String(length=200), nullable=False),
    sa.Column('postal_code', sa.String(length=20), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('bank_name', sa.String(length=200), nullable=False),
    sa.Column('iban', sa.String(length=34), nullable=False),
    sa.Column('mandate_place', sa.String(length=100), nullable=True),
    sa.Column('mandate_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index(op.f('ix_bank_accounts_id'), 'bank_accounts', ['id'], unique=False)
    op.create_table('consents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('data_protection_consent', sa.Boolean(), nullable=False),
    sa.Column('data_protection_signed_name', sa.String(length=200), nullable=True),
    sa.Column('data_protection_signed_place', sa.String(length=100), nullable=True),
    sa.Column('data_protection_signed_date', sa.Date(), nullable=True),
    sa.Column('newsletter_opt_in', sa.Boolean(), nullable=False),
    sa.Column('photo_video_consent', sa.Boolean(), nullable=False),
    sa.Column('photo_video_signed_name', sa.String(length=200), nullable=True),
    sa.Column('photo_video_signed_place', sa.String(length=100), nullable=True),
    sa.Column('photo_video_signed_date', sa.Date(), nullable=True),
    sa.Column('guardian_signed_name', sa.String(length=200), nullable=True),
    sa.Column('minor_signed_name', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('member_id')
    )
    op.create_index(op.f('ix_consents_id'), 'consents', ['id'], unique=False)
    op.create_table('documents',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('member_id', sa.Integer(), nullable=False),
    sa.Column('document_type', sa.String(length=100), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_documents_id'), 'documents', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_documents_id'), table_name='documents')
    op.drop_table('documents')
    op.drop_index(op.f('ix_consents_id'), table_name='consents')
    op.drop_table('consents')
    op.drop_index(op.f('ix_bank_accounts_id'), table_name='bank_accounts')
    op.drop_table('bank_accounts')
    op.drop_index(op.f('ix_members_id'), table_name='members')
    op.drop_table('members')
    # ### end Alembic commands ###