"""add all tables

Revision ID: 7e16dca929b6
Revises: 
Create Date: 2026-07-17 09:33:41.451565

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7e16dca929b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bank_accounts')
    op.drop_table('members')
    op.drop_table('documents')
    op.drop_table('consents')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('consents',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('member_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('privacy_consent', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=False),
    sa.Column('newsletter_consent', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('media_consent', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('minor_consent_required', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=False),
    sa.Column('minor_guardian_name', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('minor_guardian_signed_date', sa.DATE(), nullable=True),
    sa.Column('signed_date', sa.DATE(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_consents_member'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('documents',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('member_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('file_path', mysql.VARCHAR(length=300), nullable=False),
    sa.Column('file_type', mysql.ENUM('pdf', 'jpg', 'png'), nullable=False),
    sa.Column('uploaded_by', mysql.VARCHAR(length=150), nullable=True),
    sa.Column('uploaded_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_documents_member'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('members',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('first_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('last_name', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('title', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('gender', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('birth_date', sa.DATE(), nullable=False),
    sa.Column('membership_type', mysql.ENUM('Einzelperson', 'Familie', 'Student', 'Unternehmer'), nullable=False),
    sa.Column('family_members', mysql.TEXT(), nullable=True),
    sa.Column('street', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('zip_code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('phone', mysql.VARCHAR(length=50), nullable=True),
    sa.Column('email', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('join_date', sa.DATE(), nullable=False),
    sa.Column('status', mysql.ENUM('active', 'resigned'), server_default=sa.text("'active'"), nullable=True),
    sa.Column('newsletter_opt_in', mysql.TINYINT(display_width=1), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_table('bank_accounts',
    sa.Column('id', mysql.INTEGER(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('member_id', mysql.INTEGER(unsigned=True), autoincrement=False, nullable=False),
    sa.Column('account_holder_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('street', mysql.VARCHAR(length=200), nullable=False),
    sa.Column('zip_code', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('city', mysql.VARCHAR(length=100), nullable=False),
    sa.Column('bank_name', mysql.VARCHAR(length=150), nullable=False),
    sa.Column('bic', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('iban', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('mandate_signed_date', sa.DATE(), nullable=False),
    sa.Column('created_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.ForeignKeyConstraint(['member_id'], ['members.id'], name=op.f('fk_bank_member'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###